---
name: Encode-RAD50
version: 0.004
author:
  - Tom Wyant (wyant at cpan dot org)
abstract: Convert to and from the Rad50 character set
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Encode: 0
  Encode::Encoding: 0
provides:
  Encode::RAD50:
    file: lib/Encode/RAD50.pm
    version: 0.004
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
